# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)


Empresa.delete_all
Empresa.create(:nombre => "Saga")
Empresa.create(:nombre => "Ripley")

Cupon.delete_all
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Saga').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Saga').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Saga').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Saga').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Saga').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)
Cupon.create(:nombre => "Lorem Ipsum", :precio_normal => "200", :precio_dcto => "100", :descripcion => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.", :stock => "5", :empresa_id => Empresa.find_by_nombre('Ripley').id)

